#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/laurel_sprout

PRODUCT_COPY_FILES += \
    vendor/xiaomi/laurel_sprout/proprietary/etc/permissions/privapp-permissions-qti.xml:$(TARGET_COPY_OUT_ETC)/permissions/privapp-permissions-qti.xml \
    vendor/xiaomi/laurel_sprout/proprietary/odm/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_ODM)/etc/media_profiles_V1_0.xml \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/audiosphere.xml \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/xiaomi/laurel_sprout/proprietary/system_ext/etc/sysconfig/qti_whitelist_system_ext.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_whitelist_system_ext.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/camera/fonts/MFYueYuan-Regular.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MFYueYuan-Regular.ttf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/camera/fonts/MI+LanTing_GB+Outside+YS_V2.3_20160322.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MI+LanTing_GB+Outside+YS_V2.3_20160322.ttf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/camera/fonts/MIUI_Time.ttf:$(TARGET_COPY_OUT_VENDOR)/camera/fonts/MIUI_Time.ttf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Codec_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Bluetooth_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Codec_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_General_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Global_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Handset_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Hdmi_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Headset_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Speaker_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_workspaceFile.qwsp \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/CFR_para.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_F2_src1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_F2_src1.dat \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_F2_src2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_F2_src2.dat \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/MIUI_Time.ttf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/MIUI_Time.ttf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/Miui-Light.ttf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/Miui-Light.ttf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/beauty_ui9_intelligent_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beauty_ui9_intelligent_params.config \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/cameraconfig.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cameraconfig.txt \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/female_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_bg.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/female_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_icon.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/goldResult_582.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/goldResult_582.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/goldResult_586.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/goldResult_586.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_gc2375_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_gc2375_qtech_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_gc2375_qtech_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_gc2375_qtech_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx582_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx582_qtech_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx582_qtech_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx582_qtech_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx586_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx586_qtech_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx586_qtech_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx586_qtech_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx586_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx586_sunny_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx586_sunny_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx586_sunny_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_ov02a10_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_ov02a10_sunny_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_ov02a10_sunny_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_ov02a10_sunny_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5k4h7_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5k4h7_qtech_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5k4h7_qtech_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5k4h7_qtech_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5k4h7_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5k4h7_sunny_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5k4h7_sunny_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5k4h7_sunny_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_ofilm_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_ofilm_global_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_ofilm_global_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_ofilm_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_ofilm_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_sunny_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_sunny_global_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_sunny_global_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_sunny_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_sunny_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/lf_facerank_model.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lf_facerank_model.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/libalfpc_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/libalfpc_tuning.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/male_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_bg.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/male_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_icon.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/score_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_bg.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/score_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_icon.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/sdm660_camera_global.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm660_camera_global.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/sdm660_camera_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm660_camera_india.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/charger_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fstab.qti \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/profileSlm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileSlm.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/slm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/slm.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/flp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/flp.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-qti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/init.qdmastats.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qdmastats.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.adsprpc-sscrpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-sscrpc-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.1-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.qccvndhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qccvndhal@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/media_profiles_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_vendor.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/seccomp_policy/atfwd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/seccomp_policy/codec2.vendor.base.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.base.policy \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext.policy \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmi160_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_default_sensors.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_ak991x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_bmi160_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_gpio129_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_gpio129_sx932x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_gpio131_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_gpio131_sx932x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_stk3x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_stk3x3x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/stk3x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk3x3x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sx932x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine-high.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-high.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-map.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-nolimits.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-normal.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.b00 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.b01 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.b02 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.elf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.mdt \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a612_rgmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a612_rgmu.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a618_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a618_gmu.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_gmu.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a640_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a640_gmu.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_12_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_1.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/focaltech-ft3518-sumsung.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-ft3518-sumsung.ini \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/gtx8_limits.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/gtx8_limits.csv \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/lib/mibokeh_660_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_660_opencl.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    android.hardware.camera.provider@2.4-external \
    android.hardware.camera.provider@2.4-legacy \
    camera.device@1.0-impl \
    camera.device@3.2-impl \
    camera.device@3.3-impl \
    camera.device@3.4-external-impl \
    camera.device@3.4-impl \
    camera.device@3.5-external-impl \
    camera.device@3.5-impl \
    camera.device@3.6-external-impl \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.camera.provider@2.4-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vulkan.adreno \
    libC2D2 \
    libCB \
    libOpenCL \
    libQSEEComAPI \
    libVkLayer_q3dtools \
    libadreno_app_profiles \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libbt-hidlclient \
    libbtnv \
    libc2d30_bltlib \
    libcapiv2svacnn \
    libcapiv2vop \
    libcdsp_default_listener \
    libcdsprpc \
    libconfigdb \
    libdiag \
    libdsi_netctrl \
    libdsutils \
    libfastcvdsp_stub \
    libfastcvopt \
    libgpudataproducer \
    libgsl \
    libidl \
    libllvm-glnext \
    libllvm-qcom \
    libmdmdetect \
    libmdsprpc \
    libminkdescriptor \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmosal_vendor \
    libnetmgr \
    libpvr \
    libqcbor \
    libqcci_legacy \
    libqcmaputils \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdsprpc \
    libseemore \
    libsensorslog \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsnsapi \
    libsnsdiaglog \
    libssc \
    libsysmon_cdsp_skel \
    libthermalclient \
    libxml \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.camera.device@3.2 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.vpp@1.3 \
    audio.primary.laurel_sprout \
    camera.trinket \
    libFaceGrade \
    libFileMux_proprietary \
    libSNPE \
    libVDClearShot \
    libVDSuperPhotoAPI \
    libXMFD_AgeGender \
    lib_lowlight \
    liba2dpoffload_laurel_sprout \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_ad5816g \
    libactuator_ad5823 \
    libactuator_ak7345 \
    libactuator_ak7371 \
    libactuator_bu64244gwz \
    libactuator_bu64297 \
    libactuator_dw9714 \
    libactuator_dw9716 \
    libactuator_dw9718s \
    libactuator_dw9761b \
    libactuator_dw9763 \
    libactuator_dw9763b \
    libactuator_dw9790a \
    libactuator_dw9800 \
    libactuator_dw9800_imx582 \
    libactuator_laurus_dw9800w_qtech \
    libactuator_lc898122 \
    libactuator_lc898212xd \
    libactuator_lc898212xd_qc2002 \
    libactuator_lc898217xc \
    libactuator_pseudo \
    libactuator_rohm_bu64243gwz \
    libadiertac \
    libadm \
    libadpcmdec \
    libalCFR \
    libalLDC \
    libalhLDC \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_supernight \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioconfigstore \
    libaudioparsers \
    libc++_shared \
    libcamera_scene \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_india_laurus_gc2375_qtech_HDR_cpp_snapshot \
    libchromatix_india_laurus_gc2375_qtech_HDR_snapshot \
    libchromatix_india_laurus_gc2375_qtech_HDR_zsl_preview_dw9800w \
    libchromatix_india_laurus_gc2375_qtech_common \
    libchromatix_india_laurus_gc2375_qtech_cpp_ds_chromatix \
    libchromatix_india_laurus_gc2375_qtech_cpp_liveshot \
    libchromatix_india_laurus_gc2375_qtech_cpp_preview \
    libchromatix_india_laurus_gc2375_qtech_cpp_snapshot \
    libchromatix_india_laurus_gc2375_qtech_cpp_us_chromatix \
    libchromatix_india_laurus_gc2375_qtech_cpp_video \
    libchromatix_india_laurus_gc2375_qtech_cpp_video_full \
    libchromatix_india_laurus_gc2375_qtech_cpp_video_weixin \
    libchromatix_india_laurus_gc2375_qtech_default_preview_bu64297 \
    libchromatix_india_laurus_gc2375_qtech_default_video \
    libchromatix_india_laurus_gc2375_qtech_default_video_bu64297 \
    libchromatix_india_laurus_gc2375_qtech_hht_cpp_snapshot \
    libchromatix_india_laurus_gc2375_qtech_panorama_cpp_snapshot \
    libchromatix_india_laurus_gc2375_qtech_panorama_snapshot \
    libchromatix_india_laurus_gc2375_qtech_panorama_zsl_preview_dw9800w \
    libchromatix_india_laurus_gc2375_qtech_postproc \
    libchromatix_india_laurus_gc2375_qtech_preview \
    libchromatix_india_laurus_gc2375_qtech_snapshot \
    libchromatix_india_laurus_gc2375_qtech_video_full \
    libchromatix_india_laurus_gc2375_qtech_video_weixin \
    libchromatix_india_laurus_gc2375_qtech_weixin_zsl_preview_dw9800w \
    libchromatix_india_laurus_gc2375_qtech_zsl_preview_bu64297 \
    libchromatix_india_laurus_gc2375_qtech_zsl_video_bu64297 \
    libchromatix_india_laurus_imx582_qtech_4k_preview_3a \
    libchromatix_india_laurus_imx582_qtech_4k_video_3a \
    libchromatix_india_laurus_imx582_qtech_common \
    libchromatix_india_laurus_imx582_qtech_cpp_hfr_120 \
    libchromatix_india_laurus_imx582_qtech_cpp_hfr_60 \
    libchromatix_india_laurus_imx582_qtech_cpp_hfr_90 \
    libchromatix_india_laurus_imx582_qtech_cpp_liveshot \
    libchromatix_india_laurus_imx582_qtech_cpp_preview \
    libchromatix_india_laurus_imx582_qtech_cpp_snapshot \
    libchromatix_india_laurus_imx582_qtech_cpp_video \
    libchromatix_india_laurus_imx582_qtech_cpp_video_4k \
    libchromatix_india_laurus_imx582_qtech_default_preview_3a \
    libchromatix_india_laurus_imx582_qtech_default_video \
    libchromatix_india_laurus_imx582_qtech_default_video_3a \
    libchromatix_india_laurus_imx582_qtech_default_video_4k \
    libchromatix_india_laurus_imx582_qtech_hfr_120 \
    libchromatix_india_laurus_imx582_qtech_hfr_120_3a \
    libchromatix_india_laurus_imx582_qtech_hfr_60 \
    libchromatix_india_laurus_imx582_qtech_hfr_60_3a \
    libchromatix_india_laurus_imx582_qtech_hfr_90 \
    libchromatix_india_laurus_imx582_qtech_hfr_90_3a \
    libchromatix_india_laurus_imx582_qtech_postproc \
    libchromatix_india_laurus_imx582_qtech_preview \
    libchromatix_india_laurus_imx582_qtech_snapshot \
    libchromatix_india_laurus_imx582_qtech_zsl_preview_3a \
    libchromatix_india_laurus_imx582_qtech_zsl_video_3a \
    libchromatix_india_laurus_imx586_qtech_48M_cpp_snapshot \
    libchromatix_india_laurus_imx586_qtech_48M_zsl_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_HDR_zsl_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_common \
    libchromatix_india_laurus_imx586_qtech_cpp_ds_chromatix \
    libchromatix_india_laurus_imx586_qtech_cpp_hfr_120 \
    libchromatix_india_laurus_imx586_qtech_cpp_hfr_60 \
    libchromatix_india_laurus_imx586_qtech_cpp_hfr_90 \
    libchromatix_india_laurus_imx586_qtech_cpp_liveshot \
    libchromatix_india_laurus_imx586_qtech_cpp_preview \
    libchromatix_india_laurus_imx586_qtech_cpp_snapshot \
    libchromatix_india_laurus_imx586_qtech_cpp_us_chromatix \
    libchromatix_india_laurus_imx586_qtech_cpp_video \
    libchromatix_india_laurus_imx586_qtech_cpp_video_full \
    libchromatix_india_laurus_imx586_qtech_cpp_video_weixin \
    libchromatix_india_laurus_imx586_qtech_default_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_default_video \
    libchromatix_india_laurus_imx586_qtech_default_video_dw9800w \
    libchromatix_india_laurus_imx586_qtech_hfr_120 \
    libchromatix_india_laurus_imx586_qtech_hfr_120_dw9800w \
    libchromatix_india_laurus_imx586_qtech_hfr_60 \
    libchromatix_india_laurus_imx586_qtech_hfr_60_dw9800w \
    libchromatix_india_laurus_imx586_qtech_hfr_90 \
    libchromatix_india_laurus_imx586_qtech_hfr_90_dw9800w \
    libchromatix_india_laurus_imx586_qtech_hht_cpp_snapshot \
    libchromatix_india_laurus_imx586_qtech_postproc \
    libchromatix_india_laurus_imx586_qtech_preview \
    libchromatix_india_laurus_imx586_qtech_snapshot \
    libchromatix_india_laurus_imx586_qtech_video_full \
    libchromatix_india_laurus_imx586_qtech_video_weixin \
    libchromatix_india_laurus_imx586_qtech_weixin_zsl_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_zsl_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_zsl_video_dw9800w \
    libchromatix_india_laurus_ov02a10_sunny_HDR_cpp_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_HDR_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_HDR_zsl_preview_dw9800w \
    libchromatix_india_laurus_ov02a10_sunny_common \
    libchromatix_india_laurus_ov02a10_sunny_cpp_ds_chromatix \
    libchromatix_india_laurus_ov02a10_sunny_cpp_liveshot \
    libchromatix_india_laurus_ov02a10_sunny_cpp_preview \
    libchromatix_india_laurus_ov02a10_sunny_cpp_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_cpp_us_chromatix \
    libchromatix_india_laurus_ov02a10_sunny_cpp_video \
    libchromatix_india_laurus_ov02a10_sunny_cpp_video_full \
    libchromatix_india_laurus_ov02a10_sunny_cpp_video_weixin \
    libchromatix_india_laurus_ov02a10_sunny_default_preview_bu64297 \
    libchromatix_india_laurus_ov02a10_sunny_default_video \
    libchromatix_india_laurus_ov02a10_sunny_default_video_bu64297 \
    libchromatix_india_laurus_ov02a10_sunny_hht_cpp_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_panorama_cpp_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_panorama_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_panorama_zsl_preview_dw9800w \
    libchromatix_india_laurus_ov02a10_sunny_postproc \
    libchromatix_india_laurus_ov02a10_sunny_preview \
    libchromatix_india_laurus_ov02a10_sunny_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_video_full \
    libchromatix_india_laurus_ov02a10_sunny_video_weixin \
    libchromatix_india_laurus_ov02a10_sunny_weixin_zsl_preview_dw9800w \
    libchromatix_india_laurus_ov02a10_sunny_zsl_preview_bu64297 \
    libchromatix_india_laurus_ov02a10_sunny_zsl_video_bu64297 \
    libchromatix_laurus_gc2375_qtech_HDR_cpp_snapshot \
    libchromatix_laurus_gc2375_qtech_HDR_snapshot \
    libchromatix_laurus_gc2375_qtech_HDR_zsl_preview_dw9800w \
    libchromatix_laurus_gc2375_qtech_common \
    libchromatix_laurus_gc2375_qtech_cpp_ds_chromatix \
    libchromatix_laurus_gc2375_qtech_cpp_liveshot \
    libchromatix_laurus_gc2375_qtech_cpp_preview \
    libchromatix_laurus_gc2375_qtech_cpp_snapshot \
    libchromatix_laurus_gc2375_qtech_cpp_us_chromatix \
    libchromatix_laurus_gc2375_qtech_cpp_video \
    libchromatix_laurus_gc2375_qtech_cpp_video_full \
    libchromatix_laurus_gc2375_qtech_cpp_video_weixin \
    libchromatix_laurus_gc2375_qtech_default_preview_bu64297 \
    libchromatix_laurus_gc2375_qtech_default_video \
    libchromatix_laurus_gc2375_qtech_default_video_bu64297 \
    libchromatix_laurus_gc2375_qtech_hht_cpp_snapshot \
    libchromatix_laurus_gc2375_qtech_panorama_cpp_snapshot \
    libchromatix_laurus_gc2375_qtech_panorama_snapshot \
    libchromatix_laurus_gc2375_qtech_panorama_zsl_preview_dw9800w \
    libchromatix_laurus_gc2375_qtech_postproc \
    libchromatix_laurus_gc2375_qtech_preview \
    libchromatix_laurus_gc2375_qtech_snapshot \
    libchromatix_laurus_gc2375_qtech_video_full \
    libchromatix_laurus_gc2375_qtech_video_weixin \
    libchromatix_laurus_gc2375_qtech_weixin_zsl_preview_dw9800w \
    libchromatix_laurus_gc2375_qtech_zsl_preview_bu64297 \
    libchromatix_laurus_gc2375_qtech_zsl_video_bu64297 \
    libchromatix_laurus_imx582_qtech_common \
    libchromatix_laurus_imx582_qtech_common_torch \
    libchromatix_laurus_imx582_qtech_cpp_ds_chromatix \
    libchromatix_laurus_imx582_qtech_cpp_hfr_120 \
    libchromatix_laurus_imx582_qtech_cpp_hfr_240 \
    libchromatix_laurus_imx582_qtech_cpp_hfr_60 \
    libchromatix_laurus_imx582_qtech_cpp_hfr_90 \
    libchromatix_laurus_imx582_qtech_cpp_liveshot \
    libchromatix_laurus_imx582_qtech_cpp_preview \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_12M \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_12M_hht \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_12M_sr \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_48M \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_48M_hht \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_HDR \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_panorama \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_portrait \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_sn \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_torch \
    libchromatix_laurus_imx582_qtech_cpp_us_chromatix \
    libchromatix_laurus_imx582_qtech_cpp_video \
    libchromatix_laurus_imx582_qtech_cpp_video_1080P \
    libchromatix_laurus_imx582_qtech_cpp_video_4k \
    libchromatix_laurus_imx582_qtech_cpp_video_720P \
    libchromatix_laurus_imx582_qtech_cpp_video_weixin \
    libchromatix_laurus_imx582_qtech_default_preview \
    libchromatix_laurus_imx582_qtech_default_video \
    libchromatix_laurus_imx582_qtech_hfr_120 \
    libchromatix_laurus_imx582_qtech_hfr_240 \
    libchromatix_laurus_imx582_qtech_hfr_60 \
    libchromatix_laurus_imx582_qtech_hfr_90 \
    libchromatix_laurus_imx582_qtech_post_proc \
    libchromatix_laurus_imx582_qtech_preview \
    libchromatix_laurus_imx582_qtech_snapshot_12M \
    libchromatix_laurus_imx582_qtech_snapshot_12M_hht \
    libchromatix_laurus_imx582_qtech_snapshot_48M \
    libchromatix_laurus_imx582_qtech_snapshot_HDR \
    libchromatix_laurus_imx582_qtech_snapshot_panorama \
    libchromatix_laurus_imx582_qtech_snapshot_portrait \
    libchromatix_laurus_imx582_qtech_snapshot_sn \
    libchromatix_laurus_imx582_qtech_snapshot_torch \
    libchromatix_laurus_imx582_qtech_video \
    libchromatix_laurus_imx582_qtech_video_weixin \
    libchromatix_laurus_imx582_qtech_zsl_hfr_120 \
    libchromatix_laurus_imx582_qtech_zsl_hfr_240 \
    libchromatix_laurus_imx582_qtech_zsl_hfr_60 \
    libchromatix_laurus_imx582_qtech_zsl_hfr_90 \
    libchromatix_laurus_imx582_qtech_zsl_preview_12M \
    libchromatix_laurus_imx582_qtech_zsl_preview_48M \
    libchromatix_laurus_imx582_qtech_zsl_preview_HDR \
    libchromatix_laurus_imx582_qtech_zsl_preview_panorma \
    libchromatix_laurus_imx582_qtech_zsl_preview_portrait \
    libchromatix_laurus_imx582_qtech_zsl_preview_sn \
    libchromatix_laurus_imx582_qtech_zsl_preview_torch \
    libchromatix_laurus_imx582_qtech_zsl_video \
    libchromatix_laurus_imx582_qtech_zsl_video_4k \
    libchromatix_laurus_imx582_qtech_zsl_video_weixin \
    libchromatix_laurus_imx586_qtech_48M_cpp_snapshot \
    libchromatix_laurus_imx586_qtech_48M_zsl_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_HDR_zsl_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_common \
    libchromatix_laurus_imx586_qtech_cpp_ds_chromatix \
    libchromatix_laurus_imx586_qtech_cpp_hfr_120 \
    libchromatix_laurus_imx586_qtech_cpp_hfr_60 \
    libchromatix_laurus_imx586_qtech_cpp_hfr_90 \
    libchromatix_laurus_imx586_qtech_cpp_liveshot \
    libchromatix_laurus_imx586_qtech_cpp_preview \
    libchromatix_laurus_imx586_qtech_cpp_snapshot \
    libchromatix_laurus_imx586_qtech_cpp_us_chromatix \
    libchromatix_laurus_imx586_qtech_cpp_video \
    libchromatix_laurus_imx586_qtech_cpp_video_full \
    libchromatix_laurus_imx586_qtech_cpp_video_weixin \
    libchromatix_laurus_imx586_qtech_default_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_default_video \
    libchromatix_laurus_imx586_qtech_default_video_dw9800w \
    libchromatix_laurus_imx586_qtech_hfr_120 \
    libchromatix_laurus_imx586_qtech_hfr_120_dw9800w \
    libchromatix_laurus_imx586_qtech_hfr_60 \
    libchromatix_laurus_imx586_qtech_hfr_60_dw9800w \
    libchromatix_laurus_imx586_qtech_hfr_90 \
    libchromatix_laurus_imx586_qtech_hfr_90_dw9800w \
    libchromatix_laurus_imx586_qtech_hht_cpp_snapshot \
    libchromatix_laurus_imx586_qtech_postproc \
    libchromatix_laurus_imx586_qtech_preview \
    libchromatix_laurus_imx586_qtech_snapshot \
    libchromatix_laurus_imx586_qtech_video_full \
    libchromatix_laurus_imx586_qtech_video_weixin \
    libchromatix_laurus_imx586_qtech_weixin_zsl_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_zsl_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_zsl_video_dw9800w \
    libchromatix_laurus_imx586_sunny_common \
    libchromatix_laurus_imx586_sunny_common_torch \
    libchromatix_laurus_imx586_sunny_cpp_ds_chromatix \
    libchromatix_laurus_imx586_sunny_cpp_hfr_120 \
    libchromatix_laurus_imx586_sunny_cpp_hfr_240 \
    libchromatix_laurus_imx586_sunny_cpp_hfr_60 \
    libchromatix_laurus_imx586_sunny_cpp_hfr_90 \
    libchromatix_laurus_imx586_sunny_cpp_liveshot \
    libchromatix_laurus_imx586_sunny_cpp_preview \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_12M \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_12M_hht \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_12M_sr \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_48M \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_48M_hht \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_panorama \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_portrait \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_sn \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_torch \
    libchromatix_laurus_imx586_sunny_cpp_us_chromatix \
    libchromatix_laurus_imx586_sunny_cpp_video \
    libchromatix_laurus_imx586_sunny_cpp_video_1080P \
    libchromatix_laurus_imx586_sunny_cpp_video_4k \
    libchromatix_laurus_imx586_sunny_cpp_video_720P \
    libchromatix_laurus_imx586_sunny_cpp_video_weixin \
    libchromatix_laurus_imx586_sunny_default_preview \
    libchromatix_laurus_imx586_sunny_default_video \
    libchromatix_laurus_imx586_sunny_hfr_120 \
    libchromatix_laurus_imx586_sunny_hfr_240 \
    libchromatix_laurus_imx586_sunny_hfr_60 \
    libchromatix_laurus_imx586_sunny_hfr_90 \
    libchromatix_laurus_imx586_sunny_post_proc \
    libchromatix_laurus_imx586_sunny_preview \
    libchromatix_laurus_imx586_sunny_snapshot_12M \
    libchromatix_laurus_imx586_sunny_snapshot_12M_hht \
    libchromatix_laurus_imx586_sunny_snapshot_48M \
    libchromatix_laurus_imx586_sunny_snapshot_HDR \
    libchromatix_laurus_imx586_sunny_snapshot_panorama \
    libchromatix_laurus_imx586_sunny_snapshot_portrait \
    libchromatix_laurus_imx586_sunny_snapshot_sn \
    libchromatix_laurus_imx586_sunny_snapshot_torch \
    libchromatix_laurus_imx586_sunny_video \
    libchromatix_laurus_imx586_sunny_video_weixin \
    libchromatix_laurus_imx586_sunny_zsl_hfr_120 \
    libchromatix_laurus_imx586_sunny_zsl_hfr_240 \
    libchromatix_laurus_imx586_sunny_zsl_hfr_60 \
    libchromatix_laurus_imx586_sunny_zsl_hfr_90 \
    libchromatix_laurus_imx586_sunny_zsl_preview_12M \
    libchromatix_laurus_imx586_sunny_zsl_preview_48M \
    libchromatix_laurus_imx586_sunny_zsl_preview_HDR \
    libchromatix_laurus_imx586_sunny_zsl_preview_panorma \
    libchromatix_laurus_imx586_sunny_zsl_preview_portrait \
    libchromatix_laurus_imx586_sunny_zsl_preview_sn \
    libchromatix_laurus_imx586_sunny_zsl_preview_torch \
    libchromatix_laurus_imx586_sunny_zsl_video \
    libchromatix_laurus_imx586_sunny_zsl_video_4k \
    libchromatix_laurus_imx586_sunny_zsl_video_weixin \
    libchromatix_laurus_indian_imx586_sunny_common \
    libchromatix_laurus_indian_imx586_sunny_common_torch \
    libchromatix_laurus_indian_imx586_sunny_cpp_hfr_120 \
    libchromatix_laurus_indian_imx586_sunny_cpp_hfr_240 \
    libchromatix_laurus_indian_imx586_sunny_cpp_hfr_60 \
    libchromatix_laurus_indian_imx586_sunny_cpp_hfr_90 \
    libchromatix_laurus_indian_imx586_sunny_cpp_liveshot \
    libchromatix_laurus_indian_imx586_sunny_cpp_preview \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_12M \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_12M_hht \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_12M_sr \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_48M \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_48M_hht \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_panorama \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_portrait \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_sn \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_torch \
    libchromatix_laurus_indian_imx586_sunny_cpp_video \
    libchromatix_laurus_indian_imx586_sunny_cpp_video_1080P \
    libchromatix_laurus_indian_imx586_sunny_cpp_video_4k \
    libchromatix_laurus_indian_imx586_sunny_cpp_video_720P \
    libchromatix_laurus_indian_imx586_sunny_cpp_video_weixin \
    libchromatix_laurus_indian_imx586_sunny_hfr_120 \
    libchromatix_laurus_indian_imx586_sunny_hfr_240 \
    libchromatix_laurus_indian_imx586_sunny_hfr_60 \
    libchromatix_laurus_indian_imx586_sunny_hfr_90 \
    libchromatix_laurus_indian_imx586_sunny_post_proc \
    libchromatix_laurus_indian_imx586_sunny_preview \
    libchromatix_laurus_indian_imx586_sunny_snapshot_12M \
    libchromatix_laurus_indian_imx586_sunny_snapshot_48M \
    libchromatix_laurus_indian_imx586_sunny_snapshot_panorama \
    libchromatix_laurus_indian_imx586_sunny_snapshot_portrait \
    libchromatix_laurus_indian_imx586_sunny_snapshot_sn \
    libchromatix_laurus_indian_imx586_sunny_snapshot_torch \
    libchromatix_laurus_indian_imx586_sunny_video \
    libchromatix_laurus_indian_imx586_sunny_video_weixin \
    libchromatix_laurus_indian_imx586_sunny_zsl_hfr_120 \
    libchromatix_laurus_indian_imx586_sunny_zsl_hfr_240 \
    libchromatix_laurus_indian_imx586_sunny_zsl_hfr_60 \
    libchromatix_laurus_indian_imx586_sunny_zsl_hfr_90 \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_12M \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_48M \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_HDR \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_panorma \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_portrait \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_sn \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_torch \
    libchromatix_laurus_indian_imx586_sunny_zsl_video \
    libchromatix_laurus_indian_imx586_sunny_zsl_video_4k \
    libchromatix_laurus_indian_imx586_sunny_zsl_video_weixin \
    libchromatix_laurus_indian_s5k4h7_qtech_common \
    libchromatix_laurus_indian_s5k4h7_qtech_common_torch \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_liveshot \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_preview \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_snapshot \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_snapshot_HDR \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_snapshot_hht \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_snapshot_torch \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_video \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_video_1080P \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_video_720P \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_video_weixin \
    libchromatix_laurus_indian_s5k4h7_qtech_default_preview \
    libchromatix_laurus_indian_s5k4h7_qtech_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_qtech_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_qtech_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_qtech_post_proc \
    libchromatix_laurus_indian_s5k4h7_qtech_snapshot \
    libchromatix_laurus_indian_s5k4h7_qtech_snapshot_torch \
    libchromatix_laurus_indian_s5k4h7_qtech_video \
    libchromatix_laurus_indian_s5k4h7_qtech_video_weixin \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_preview \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_preview_HDR \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_preview_torch \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_video \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_video_weixin \
    libchromatix_laurus_indian_s5k4h7_sunny_common \
    libchromatix_laurus_indian_s5k4h7_sunny_common_torch \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_liveshot \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_preview \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_snapshot \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_snapshot_hht \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_snapshot_torch \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_video \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_video_1080P \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_video_720P \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_video_weixin \
    libchromatix_laurus_indian_s5k4h7_sunny_default_preview \
    libchromatix_laurus_indian_s5k4h7_sunny_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_sunny_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_sunny_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_sunny_post_proc \
    libchromatix_laurus_indian_s5k4h7_sunny_snapshot \
    libchromatix_laurus_indian_s5k4h7_sunny_snapshot_torch \
    libchromatix_laurus_indian_s5k4h7_sunny_video \
    libchromatix_laurus_indian_s5k4h7_sunny_video_weixin \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_preview \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_preview_HDR \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_preview_torch \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_video \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_video_weixin \
    libchromatix_laurus_ov02a10_sunny_HDR_cpp_snapshot \
    libchromatix_laurus_ov02a10_sunny_HDR_snapshot \
    libchromatix_laurus_ov02a10_sunny_HDR_zsl_preview_dw9800w \
    libchromatix_laurus_ov02a10_sunny_common \
    libchromatix_laurus_ov02a10_sunny_cpp_ds_chromatix \
    libchromatix_laurus_ov02a10_sunny_cpp_liveshot \
    libchromatix_laurus_ov02a10_sunny_cpp_preview \
    libchromatix_laurus_ov02a10_sunny_cpp_snapshot \
    libchromatix_laurus_ov02a10_sunny_cpp_us_chromatix \
    libchromatix_laurus_ov02a10_sunny_cpp_video \
    libchromatix_laurus_ov02a10_sunny_cpp_video_full \
    libchromatix_laurus_ov02a10_sunny_cpp_video_weixin \
    libchromatix_laurus_ov02a10_sunny_default_preview_bu64297 \
    libchromatix_laurus_ov02a10_sunny_default_video \
    libchromatix_laurus_ov02a10_sunny_default_video_bu64297 \
    libchromatix_laurus_ov02a10_sunny_hht_cpp_snapshot \
    libchromatix_laurus_ov02a10_sunny_panorama_cpp_snapshot \
    libchromatix_laurus_ov02a10_sunny_panorama_snapshot \
    libchromatix_laurus_ov02a10_sunny_panorama_zsl_preview_dw9800w \
    libchromatix_laurus_ov02a10_sunny_postproc \
    libchromatix_laurus_ov02a10_sunny_preview \
    libchromatix_laurus_ov02a10_sunny_snapshot \
    libchromatix_laurus_ov02a10_sunny_video_full \
    libchromatix_laurus_ov02a10_sunny_video_weixin \
    libchromatix_laurus_ov02a10_sunny_weixin_zsl_preview_dw9800w \
    libchromatix_laurus_ov02a10_sunny_zsl_preview_bu64297 \
    libchromatix_laurus_ov02a10_sunny_zsl_video_bu64297 \
    libchromatix_laurus_s5k4h7_qtech_common \
    libchromatix_laurus_s5k4h7_qtech_common_torch \
    libchromatix_laurus_s5k4h7_qtech_cpp_ds_chromatix \
    libchromatix_laurus_s5k4h7_qtech_cpp_hfr_120 \
    libchromatix_laurus_s5k4h7_qtech_cpp_hfr_60 \
    libchromatix_laurus_s5k4h7_qtech_cpp_hfr_90 \
    libchromatix_laurus_s5k4h7_qtech_cpp_liveshot \
    libchromatix_laurus_s5k4h7_qtech_cpp_preview \
    libchromatix_laurus_s5k4h7_qtech_cpp_snapshot \
    libchromatix_laurus_s5k4h7_qtech_cpp_snapshot_HDR \
    libchromatix_laurus_s5k4h7_qtech_cpp_snapshot_hht \
    libchromatix_laurus_s5k4h7_qtech_cpp_snapshot_torch \
    libchromatix_laurus_s5k4h7_qtech_cpp_us_chromatix \
    libchromatix_laurus_s5k4h7_qtech_cpp_video \
    libchromatix_laurus_s5k4h7_qtech_cpp_video_1080P \
    libchromatix_laurus_s5k4h7_qtech_cpp_video_720P \
    libchromatix_laurus_s5k4h7_qtech_cpp_video_weixin \
    libchromatix_laurus_s5k4h7_qtech_default_preview \
    libchromatix_laurus_s5k4h7_qtech_default_video \
    libchromatix_laurus_s5k4h7_qtech_hfr_120 \
    libchromatix_laurus_s5k4h7_qtech_hfr_60 \
    libchromatix_laurus_s5k4h7_qtech_hfr_90 \
    libchromatix_laurus_s5k4h7_qtech_post_proc \
    libchromatix_laurus_s5k4h7_qtech_preview \
    libchromatix_laurus_s5k4h7_qtech_snapshot \
    libchromatix_laurus_s5k4h7_qtech_snapshot_HDR \
    libchromatix_laurus_s5k4h7_qtech_snapshot_hht \
    libchromatix_laurus_s5k4h7_qtech_snapshot_torch \
    libchromatix_laurus_s5k4h7_qtech_video \
    libchromatix_laurus_s5k4h7_qtech_video_weixin \
    libchromatix_laurus_s5k4h7_qtech_zsl_hfr_120 \
    libchromatix_laurus_s5k4h7_qtech_zsl_hfr_60 \
    libchromatix_laurus_s5k4h7_qtech_zsl_hfr_90 \
    libchromatix_laurus_s5k4h7_qtech_zsl_preview \
    libchromatix_laurus_s5k4h7_qtech_zsl_preview_HDR \
    libchromatix_laurus_s5k4h7_qtech_zsl_preview_torch \
    libchromatix_laurus_s5k4h7_qtech_zsl_video \
    libchromatix_laurus_s5k4h7_qtech_zsl_video_weixin \
    libchromatix_laurus_s5k4h7_sunny_common \
    libchromatix_laurus_s5k4h7_sunny_common_torch \
    libchromatix_laurus_s5k4h7_sunny_cpp_ds_chromatix \
    libchromatix_laurus_s5k4h7_sunny_cpp_hfr_120 \
    libchromatix_laurus_s5k4h7_sunny_cpp_hfr_60 \
    libchromatix_laurus_s5k4h7_sunny_cpp_hfr_90 \
    libchromatix_laurus_s5k4h7_sunny_cpp_liveshot \
    libchromatix_laurus_s5k4h7_sunny_cpp_preview \
    libchromatix_laurus_s5k4h7_sunny_cpp_snapshot \
    libchromatix_laurus_s5k4h7_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_s5k4h7_sunny_cpp_snapshot_hht \
    libchromatix_laurus_s5k4h7_sunny_cpp_snapshot_torch \
    libchromatix_laurus_s5k4h7_sunny_cpp_us_chromatix \
    libchromatix_laurus_s5k4h7_sunny_cpp_video \
    libchromatix_laurus_s5k4h7_sunny_cpp_video_1080P \
    libchromatix_laurus_s5k4h7_sunny_cpp_video_720P \
    libchromatix_laurus_s5k4h7_sunny_cpp_video_weixin \
    libchromatix_laurus_s5k4h7_sunny_default_preview \
    libchromatix_laurus_s5k4h7_sunny_default_video \
    libchromatix_laurus_s5k4h7_sunny_hfr_120 \
    libchromatix_laurus_s5k4h7_sunny_hfr_60 \
    libchromatix_laurus_s5k4h7_sunny_hfr_90 \
    libchromatix_laurus_s5k4h7_sunny_post_proc \
    libchromatix_laurus_s5k4h7_sunny_preview \
    libchromatix_laurus_s5k4h7_sunny_snapshot \
    libchromatix_laurus_s5k4h7_sunny_snapshot_HDR \
    libchromatix_laurus_s5k4h7_sunny_snapshot_hht \
    libchromatix_laurus_s5k4h7_sunny_snapshot_torch \
    libchromatix_laurus_s5k4h7_sunny_video \
    libchromatix_laurus_s5k4h7_sunny_video_weixin \
    libchromatix_laurus_s5k4h7_sunny_zsl_hfr_120 \
    libchromatix_laurus_s5k4h7_sunny_zsl_hfr_60 \
    libchromatix_laurus_s5k4h7_sunny_zsl_hfr_90 \
    libchromatix_laurus_s5k4h7_sunny_zsl_preview \
    libchromatix_laurus_s5k4h7_sunny_zsl_preview_HDR \
    libchromatix_laurus_s5k4h7_sunny_zsl_preview_torch \
    libchromatix_laurus_s5k4h7_sunny_zsl_video \
    libchromatix_laurus_s5k4h7_sunny_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_common \
    libchromatix_laurus_s5kgd1_ofilm_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_cpp_liveshot \
    libchromatix_laurus_s5kgd1_ofilm_cpp_preview \
    libchromatix_laurus_s5kgd1_ofilm_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_ofilm_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_cpp_video \
    libchromatix_laurus_s5kgd1_ofilm_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_ofilm_cpp_video_720P \
    libchromatix_laurus_s5kgd1_ofilm_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_default_preview \
    libchromatix_laurus_s5kgd1_ofilm_default_video \
    libchromatix_laurus_s5kgd1_ofilm_global_common \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_liveshot \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_preview \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_video \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_video_720P \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_global_default_preview \
    libchromatix_laurus_s5kgd1_ofilm_global_default_video \
    libchromatix_laurus_s5kgd1_ofilm_global_post_proc \
    libchromatix_laurus_s5kgd1_ofilm_global_preview \
    libchromatix_laurus_s5kgd1_ofilm_global_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_global_snapshot \
    libchromatix_laurus_s5kgd1_ofilm_global_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_global_video \
    libchromatix_laurus_s5kgd1_ofilm_global_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_preview \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_video \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_india_common \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_liveshot \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_preview \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_video \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_video_720P \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_india_default_preview \
    libchromatix_laurus_s5kgd1_ofilm_india_default_video \
    libchromatix_laurus_s5kgd1_ofilm_india_post_proc \
    libchromatix_laurus_s5kgd1_ofilm_india_preview \
    libchromatix_laurus_s5kgd1_ofilm_india_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_india_snapshot \
    libchromatix_laurus_s5kgd1_ofilm_india_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_india_video \
    libchromatix_laurus_s5kgd1_ofilm_india_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_preview \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_video \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_post_proc \
    libchromatix_laurus_s5kgd1_ofilm_preview \
    libchromatix_laurus_s5kgd1_ofilm_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_snapshot \
    libchromatix_laurus_s5kgd1_ofilm_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_video \
    libchromatix_laurus_s5kgd1_ofilm_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_zsl_preview \
    libchromatix_laurus_s5kgd1_ofilm_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_ofilm_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_ofilm_zsl_video \
    libchromatix_laurus_s5kgd1_ofilm_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_common \
    libchromatix_laurus_s5kgd1_sunny_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_sunny_cpp_liveshot \
    libchromatix_laurus_s5kgd1_sunny_cpp_preview \
    libchromatix_laurus_s5kgd1_sunny_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_sunny_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_sunny_cpp_video \
    libchromatix_laurus_s5kgd1_sunny_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_sunny_cpp_video_720P \
    libchromatix_laurus_s5kgd1_sunny_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_default_preview \
    libchromatix_laurus_s5kgd1_sunny_default_video \
    libchromatix_laurus_s5kgd1_sunny_global_common \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_liveshot \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_preview \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_video \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_video_720P \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_global_default_preview \
    libchromatix_laurus_s5kgd1_sunny_global_default_video \
    libchromatix_laurus_s5kgd1_sunny_global_post_proc \
    libchromatix_laurus_s5kgd1_sunny_global_preview \
    libchromatix_laurus_s5kgd1_sunny_global_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_global_snapshot \
    libchromatix_laurus_s5kgd1_sunny_global_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_global_video \
    libchromatix_laurus_s5kgd1_sunny_global_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_preview \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_video \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_india_common \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_liveshot \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_preview \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_video \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_video_720P \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_india_default_preview \
    libchromatix_laurus_s5kgd1_sunny_india_default_video \
    libchromatix_laurus_s5kgd1_sunny_india_post_proc \
    libchromatix_laurus_s5kgd1_sunny_india_preview \
    libchromatix_laurus_s5kgd1_sunny_india_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_india_snapshot \
    libchromatix_laurus_s5kgd1_sunny_india_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_india_video \
    libchromatix_laurus_s5kgd1_sunny_india_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_preview \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_video \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_post_proc \
    libchromatix_laurus_s5kgd1_sunny_preview \
    libchromatix_laurus_s5kgd1_sunny_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_snapshot \
    libchromatix_laurus_s5kgd1_sunny_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_video \
    libchromatix_laurus_s5kgd1_sunny_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_zsl_preview \
    libchromatix_laurus_s5kgd1_sunny_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_sunny_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_sunny_zsl_video \
    libchromatix_laurus_s5kgd1_sunny_zsl_video_weixin \
    libdepthmapwrapper \
    libdng_sdkvendor \
    libdrc \
    libfastcrc \
    libflash_pmic \
    libft2vendor \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libhal_dbg \
    libhdmipassthru \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    liblistensoundmodel2 \
    libmialgo_sd \
    libmibokeh_660 \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_bokeh \
    libmmcamera_csidtg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_dw9761b_2d_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_interface \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_laurus_gc2375_qtech \
    libmmcamera_laurus_imx582_qtech \
    libmmcamera_laurus_imx586_qtech \
    libmmcamera_laurus_imx586_sunny \
    libmmcamera_laurus_ofilm_s5kgd1_eeprom \
    libmmcamera_laurus_ov02a10_sunny \
    libmmcamera_laurus_qtech_imx582_eeprom \
    libmmcamera_laurus_qtech_imx586_eeprom \
    libmmcamera_laurus_qtech_s5k4h7_eeprom \
    libmmcamera_laurus_s5k4h7_qtech \
    libmmcamera_laurus_s5k4h7_sunny \
    libmmcamera_laurus_s5kgd1_ofilm \
    libmmcamera_laurus_s5kgd1_sunny \
    libmmcamera_laurus_sunny_imx586_eeprom \
    libmmcamera_laurus_sunny_s5k4h7_eeprom \
    libmmcamera_laurus_sunny_s5kgd1_eeprom \
    libmmcamera_le2464c_eeprom \
    libmmcamera_le2464c_master_eeprom \
    libmmcamera_m24c64s_eeprom \
    libmmcamera_onsemi_cat24c16_eeprom \
    libmmcamera_onsemi_cat24c32_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_qtech_f3l8yam_eeprom \
    libmmcamera_qtech_f5670bq_eeprom \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_sat_test_lib \
    libmmcamera_stillmore_lib \
    libmmcamera_sunny_8865_eeprom \
    libmmcamera_sunny_q13v06k_eeprom \
    libmmcamera_sunny_q5v41b_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_truly_cma481_eeprom \
    libmmcamera_truly_cmb433_eeprom \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmmrtpdecoder_proprietary \
    libmmrtpencoder_proprietary \
    libmpbase \
    libmulawdec \
    libois_bu63165 \
    libois_lc898122 \
    libqcodec2 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libqtigef \
    libremosaic_daemon \
    libsmwrapper \
    libsurround_3mic_proc \
    libsymphony-cpu \
    libsymphonypower \
    libvideoutils \
    libvidhance \
    libwfdcommonutils_proprietary \
    libwfddisplayconfig_proprietary \
    libwfdmmservice_proprietary \
    libwfdutils_proprietary \
    miwatermark \
    libasphere \
    libmisoundfx \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    vendor.qti.hardware.scve.objecttracker@1.0 \
    vendor.qti.hardware.scve.panorama@1.0 \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.gnss@2.1-impl-qti \
    consumerir.trinket \
    fingerprint.goodix_fod.default \
    vendor.qti.esepowermanager@1.1-impl \
    vendor.qti.gnss@4.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.qccvndhal@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    vendor.qti.hardware.soter@1.0-impl \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libQTEEConnector_vendor \
    libSecureUILib \
    libStDrvInt \
    libaoa \
    libbatching \
    libcacertclient \
    libcdfw \
    libcdfw_remote_api \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libcpion \
    libdataitems \
    libdisp-aba \
    libdisplayqos \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libgdtap \
    libgeofencing \
    libgf_hal \
    libgnss \
    libgnsspps \
    libgps.utils \
    libhdr_tm \
    libhexagon_nn_stub \
    libizat_client_api \
    libizat_core \
    libjnihelper \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    libloc_api_v02 \
    libloc_core \
    libloc_socket \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libminksocket \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    liboemaids_vendor \
    liboemcrypto \
    libops \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libqcc_file_agent \
    libqcrilFramework \
    libqcrildatactl \
    libqdma_file_agent \
    libqisl \
    libqrtr \
    libqseed3 \
    libqsocket \
    libqtikeymaster4 \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    librilqmiservices \
    librpmb \
    libsdedrm \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsecureui \
    libsecureui_svcsock \
    libsensorcal \
    libsettings \
    libsi \
    libslimclient \
    libsns_registry_skel \
    libsoc_helper \
    libsoc_helper_jni \
    libssc_default_listener \
    libssd \
    libsystem_health_mon \
    libtime_genoff \
    libtinyxml2_1 \
    libtrustedapploader \
    libtzdrmgenprov \
    libvendor.goodix.hardware.biometrics.fingerprint@2.1 \
    libwms \
    libwqe \
    libwvhidl \
    libxtadapter \
    libwvdrmengine \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    sensors.ssc \
    unnhal-acc-adreno \
    unnhal-acc-common \
    unnhal-acc-hvx \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.esepowermanager@1.1 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0-service \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fingerprintext@1.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccvndhal@1.0-halimpl \
    vendor.qti.hardware.qccvndhal@1.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qcriNvOpt@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    capi_v2_aptX_CLHDAD_Encoder \
    libVC1Dec \
    libVC1DecDsp_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhexagon_nn_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsns_device_mode_skel \
    libsns_low_lat_stream_skel \
    misound_res \
    libmmosal \
    libmmparser_lite \
    libmmrtpdecoder \
    libmmrtpencoder \
    com.qualcomm.qti.dpm.api@1.0 \
    fm_helium \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libfm-hci \
    libimscamera_jni \
    libimsmedia_jni \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    CACertService \
    CneApp \
    IWlanService \
    QCC-TR-UI \
    TimeService \
    PowerOffAlarm \
    QtiTelephonyService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    tcmclient \
    audiosphere \
    com.qti.dpmframework \
    dpmapi \
    qcrilhook \
    vendor.qti.hardware.alarm-V1.0-java \
    android.hardware.gnss@2.1-service-qti.xml \
    android.hardware.neuralnetworks@1.3-service-qti.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vendor.qti.gnss@4.0-service.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    cdsprpcd \
    cnd \
    cnss-daemon \
    dpmQmiMgr \
    dspservice \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gnss@2.1-service-qti \
    android.hardware.keymaster@4.0-service-qti \
    android.hardware.neuralnetworks@1.3-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.esepowermanager@1.1-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.qccvndhal@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.qti.media.c2@1.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    init.qti.chg_policy \
    init.qti.qcv \
    irsc_util \
    ks \
    loc_launcher \
    lowi-server \
    mlid \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    ppd \
    qcc-trd \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    sensors.qti \
    ssgqmigd \
    ssgtzd \
    tftp_server \
    thermal-engine \
    time_daemon \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent \
    dpmd

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
